### ISSUE TITLE
Check always true conditions

### ISSUE THREAD

**Issue by milenko-s** [raibisch/ESP32_ABL#1]
After cloning the repository, I got some warnings from my [static code analysis tool](https://cppcheck.sourceforge.io/).

`Condition 'c<10' is always true`
https://github.com/raibisch/ESP32_ABL/blob/cec06e7eee2dffd9ad4f0c2f3d8dc64ca6c6832a/src/main.cpp#L218C9-L218C9

Running just the function confirms this. I had to change it to `string` for my compiler. The following code behaves just like the original:
```cpp
string uint64ToString(uint64_t input)
{
  string result = "";
  uint8_t base = 10;

  do
  {
    char c = input % base;
    input /= base;

    //if (c < 10)
      c += '0';
    //else
    //  c += 'A' - 10;
    result = c + result;
  } while (input);
  return result;
}
```

There is a second occurrence of an always true condition:

`Condition 'a=0' is always false`
https://github.com/raibisch/ESP32_ABL/blob/main/src/main.cpp#L837

```cpp
if (request->argName(0) == "imax")
{
   forcePolling();
   uint a = String(request->arg(i)).toInt();
   AsyncWebLog.println("GET-SET-Imax:" + String(a)+ "A");
   if ((a >=6 && a <=16) || (a=0))
   {
       ABL_tx_Ampere = a;
       ABL_tx_status = SET_Current; // next Send Protocol
   }
   else
   {
    AsyncWebLog.println("**ERROR Imax out of range!");
   }
}
```

**Comment by raibisch** [comment]
close
