### ISSUE TITLE
ESP32 Digital In I/O used to reduce the charge current

### ISSUE THREAD

**Issue by Meins321** [raibisch/ESP32_ABL#11]
Hello!

Is it possible to use 3 pins of the ESP32 to set the charge current to a defined value?

I would like to reduce my 11kW to 60% 40% 0% if possible.
The idea is to provide 3 optocouplers for the network supplier to reduce the charge current if the network is overloaded...

Would be nice to build it inside this esp32 project

**Comment by raibisch** [comment]
yes, this is a good idea ! ..maybe in a future release (but feel free to clone the project and expand this feature). In Germany there is an simple Interface called "SG-ready" (2-Inputs with 4 logical states) 

code snipped could be something like this:

 ```
forcePolling();
ABL_tx_Icmax = 6; // or any other value from 6-16
ABL_tx_status = SET_Current;
```


What I have planned in future, is an integration of dynamic energy cost planning (e.g. Tibber)

**Comment by Meins321** [comment]
My first response would have been, well it will hit performance if tibber is also involved..
Then I found this
https://github.com/jesperalmstrom/tibber_price
Maybe worth a look.
I will buy the hardware and when my abl eMH1 goes online I will work on this too and contribute...

Seems like we will need this or go offline as cutting  phase 2 & 3 is no option to charge with 3600W

**Comment by Meins321** [comment]
Ah I did not mean to close it :-/
