### ISSUE TITLE
Flash.bat not working as instructed

### ISSUE THREAD

**Issue by Pave87** [raibisch/ESP32_ABL#12]
So trying to flash your precompiled program with flash.bat on win10.

I installed python and esptool.py and in python environment I get version of esptool.
But when running flash.bat I get error:
```
'esptool.py' is not recognized as an internal or external command,
operable program or batch file.
```
I tested to copy source from Esptool project to same directory as flash.bat and then esptool.py file is opened in editor.

What am I missing?

Also noticed that files "firmware.bin" and "spiffs.bin" do not exist in V1_2 folder. Are files in V1_1 folder what should be copied to V1_2 folder?

**Comment by raibisch** [comment]
I work (and test) only on Linux, so I have no experience in Windows, but have a look at:

[https://github.com/espressif/esptool/releases](https://github.com/espressif/esptool/releases) (there is also an Windows installation)

for the "firmware.bin" and "spiffs.bin" files:
at 
[https://github.com/raibisch/ESP32_ABL/tree/main/firmware/lolin_s2_mini/V1_2](https://github.com/raibisch/ESP32_ABL/tree/main/firmware/lolin_s2_mini/V1_2
)
I see both files (please verify again)  ;-)

**Comment by Pave87** [comment]
So I downloaded EspTool release for Windows and extracted files to same folder where flash.bat was.
Needed to remove ".py" from bat command and then it worked. 

For missing files, for some reason my first download was missing these files. I downloaded again and there files where as you said.

Thanks for help.
