### ISSUE TITLE
Missing break statement

### ISSUE THREAD

**Issue by milenko-s** [raibisch/ESP32_ABL#2]
Could you please check if a break statement is missing or if this is the expected behaviour?
`Variable 'tx' is reassigned a value before the old one has been used. 'break;' missing?`
https://github.com/raibisch/ESP32_ABL/blob/cec06e7eee2dffd9ad4f0c2f3d8dc64ca6c6832a/src/main.cpp#L437

```cpp
case 14:
    tx = String(ABL_TX_SET_14A);
break;

case 15:
   tx = String(ABL_TX_SET_15A);
// BREAK?
case 16:
    tx = String(ABL_TX_SET_16A);
break;

default:
    tx = String(ABL_TX_SET_6A);
break;
```

**Comment by raibisch** [comment]
is fixed. 
Danke ;-)
